In [1]:
import numpy as np


In [2]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
arr


array([1, 2, 3, 4, 5])

In [3]:
type(arr)


numpy.ndarray

In [4]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
matrix


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
matrix.shape


(2, 3)

In [6]:
arr.ndim      # number of dimensions


1

In [7]:
arr.shape     # shape of array


(5,)

In [8]:
arr.dtype     # data type


dtype('int32')

In [9]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [10]:
np.ones((3, 4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.rand(5)


array([0.16865681, 0.99543521, 0.02334944, 0.86171978, 0.55175703])

In [14]:
np.random.randn(5)


array([-0.03582257,  1.01537664,  0.80855222, -2.40808121, -0.40035413])

In [15]:
np.random.randint(1, 100, 10)


array([82, 89, 86, 55, 59, 80, 30, 10,  4, 74])

In [16]:
arr = np.array([10, 20, 30, 40, 50])


In [17]:
arr[0]


10

In [18]:
arr[1:4]


array([20, 30, 40])

In [19]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


In [20]:
matrix[1, 2]


60

In [21]:
matrix[:, 1]


array([20, 50, 80])

In [22]:
arr = np.array([5, 10, 15, 20, 25])


In [23]:
arr[arr > 15]


array([20, 25])

In [24]:
arr = np.array([1, 2, 3, 4])


In [25]:
arr + 10


array([11, 12, 13, 14])

In [26]:
arr * 2


array([2, 4, 6, 8])

In [27]:
arr ** 2


array([ 1,  4,  9, 16])

In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


In [29]:
arr1 + arr2


array([5, 7, 9])

In [30]:
arr1 * arr2


array([ 4, 10, 18])

In [31]:
arr = np.array([10, 20, 30, 40, 50])


In [32]:
arr.sum()


150

In [33]:
arr.mean()


30.0

In [34]:
arr.max()


50

In [35]:
arr.min()


10

In [36]:
arr.std()


14.142135623730951

In [37]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


In [38]:
matrix + 10


array([[11, 12, 13],
       [14, 15, 16]])

In [39]:
matrix * 2


array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [40]:
prices = np.array([100, 150, 200, 250])
tax_rate = 0.18

total_prices = prices + prices * tax_rate
total_prices


array([118., 177., 236., 295.])