# Numpy Array Oluşturma Yöntemleri


In [69]:
data_list = [10,20,30]


In [ ]:
data_list


In [8]:
import numpy as np


In [9]:
arr = np.array(data_list)


In [10]:
arr


array([10, 20, 30])

In [11]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [12]:
arr2 = np.array(data_list2)


In [14]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
arr

array([10, 20, 30])

In [16]:
arr[1]

20

In [17]:
arr[2]

30

In [18]:
arr2[2,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [19]:
arr2[2,2]

90

In [20]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(10,35)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [24]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.linspace(0,100,5) # 0 ile 100 arası değerleri 5 parçaya böler.

array([  0.,  25.,  50.,  75., 100.])

In [33]:
np.linspace(0,1000,25) # 0 ile 1000 arası değerleri 25 parçaya böler.

array([   0.        ,   41.66666667,   83.33333333,  125.        ,
        166.66666667,  208.33333333,  250.        ,  291.66666667,
        333.33333333,  375.        ,  416.66666667,  458.33333333,
        500.        ,  541.66666667,  583.33333333,  625.        ,
        666.66666667,  708.33333333,  750.        ,  791.66666667,
        833.33333333,  875.        ,  916.66666667,  958.33333333,
       1000.        ])

In [34]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [35]:
np.eye(6) # Birim Matris Oluşturur.


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [36]:
np.random.randint(0,10) # 0(dahil) ile 10(hariç) arasında random int oluşturur.

5

In [37]:
np.random.randint(10) # 0(dahil) ile 10(hariç) arasında random int oluşturur.

9

In [38]:
np.random.randint(1,10,5) # 1(dahil) ile 10(hariç) arasında 5 değer oluşturarak 5 değer saklayan array oluşturur.


array([3, 8, 6, 2, 3])

In [39]:
np.random.rand(5) # 0 ile 1 arasında 5 float değerler oluşturur.

array([0.09125916, 0.79561778, 0.6805543 , 0.34027614, 0.82979467])

In [40]:
np.random.randn(10) # 0 etrafında - ve + değerlerle Gaussian Distribution'a göre değerler oluşturur.


array([ 1.18449174,  0.03704743,  0.27716582,  0.36920365, -0.73272954,
        1.20260458,  0.83889421, -2.45051562, -0.78703854,  0.98359728])

In [41]:
arr = np.arange(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.reshape(5,5) # 5 x 5 =  25 tek boyutlu matrisi 2 boyuta çevirir.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.reshape(10,2) 

ValueError: cannot reshape array of size 25 into shape (10,2)

In [47]:
newArray = np.random.randint(1,100,10)


In [49]:
newArray

array([58, 53, 33, 19, 19,  5, 10, 51, 79, 82])

In [51]:
newArray.max()

82

In [52]:
newArray.min()


5

In [53]:
newArray.sum() # Tüm değerlerin toplamı


409

In [54]:
newArray.mean() # Ortalama Bulur 


40.9

In [55]:
newArray.argmin() # En küçük eleman 5.indekste


5

In [56]:
newArray.argmax() # En büyük eleman 9.indekste


9

# Determinant Hesaplama

In [58]:
detArray =  np.random.randint(1,100,25)


In [60]:
detArray

array([72, 36, 58, 39, 35, 94, 35, 72, 94, 67,  9, 75, 21, 44, 76, 85, 58,
       27, 52, 42, 67, 41, 76, 16, 27])

In [61]:
detArray = detArray.reshape(5,5)

In [62]:
detArray

array([[72, 36, 58, 39, 35],
       [94, 35, 72, 94, 67],
       [ 9, 75, 21, 44, 76],
       [85, 58, 27, 52, 42],
       [67, 41, 76, 16, 27]])

In [63]:
np.linalg.det(detArray)


29821418.999999903

In [64]:
round(np.linalg.det(detArray))

29821419

In [65]:
detArray2 = np.array([[1,2],[3,4]])

In [66]:
detArray2

array([[1, 2],
       [3, 4]])

In [67]:
round(np.linalg.det(detArray2))

-2