# Numpy Array Indekslenmesi ve Parçalanması

In [1]:
import numpy as np


In [2]:
arr = np.arange(1,10)


In [4]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[1]


2

In [6]:
arr[1:5]

array([2, 3, 4, 5])

In [7]:
arr[:4]

array([1, 2, 3, 4])

In [9]:
arr[:2]

array([1, 2])

In [13]:
arr[::2]

array([1, 3, 5, 7, 9])

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[:3] = 25

In [16]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [17]:
arr = np.arange(1,10)

In [18]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2 = arr # Aynı değerleri gösteren iki tane değişken


In [20]:
arr2[:3] =  25


In [21]:
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [22]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [23]:
arr = np.arange(1,10)


In [25]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arrCopy = arr.copy() # Değerler kopyalanıyor.


In [28]:
arrCopy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arrCopy[:3] = 25


In [31]:
arrCopy

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [32]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
newArray = np.arange(1,21)

In [35]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
newArray = newArray.reshape(4,5)

In [37]:
newArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
newArray[:,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [48]:
newArray = newArray.reshape(2,10)

In [49]:
newArray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [50]:
newArray[:,:2]

array([[ 1,  2],
       [11, 12]])

In [51]:
newArray[:2,:2]

array([[ 1,  2],
       [11, 12]])

In [53]:
newArray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [55]:
newArray[2:]

array([], shape=(0, 10), dtype=int32)

# Numpy Arraylerinin Filtrelenmesi

In [56]:
arr = np.arange(1,10)


In [58]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr > 2


array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [62]:
boolValuesArray = arr > 3



In [63]:
boolValuesArray

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [65]:
arr[boolValuesArray] # True olanlar filtrelenir.


array([4, 5, 6, 7, 8, 9])

In [66]:
arr[arr > 5] # Daha kısa hali.

array([6, 7, 8, 9])