# Numpy'ı Dahil Edin

In [1]:
import numpy as np


# 5 tane 1 barındıran bir array oluşturun

In [2]:
my_array = np.ones(5)

In [3]:
my_array

array([1., 1., 1., 1., 1.])

# 5 tane 0 barındıran bir array oluşturun

In [4]:
my_array = np.zeros(5)


In [5]:
my_array

array([0., 0., 0., 0., 0.])

# 2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun

In [6]:
my_array = np.arange(2, 101, 2)


In [7]:
my_array

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

# 5 tane 10 bulunan bir array oluşturun

In [8]:
my_array = np.full(5, 10)


In [9]:
my_array

array([10, 10, 10, 10, 10])

# 1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun


In [10]:
my_matrix = np.arange(1, 17).reshape(4, 4)


In [11]:
my_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# 4x4'lük bir birim matris oluşturun

In [12]:
my_identity_matrix = np.eye(4)


In [13]:
my_identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 0 ile 5 arasında rastgele değerler üretin

In [15]:
random_value = np.random.uniform(0, 5)


In [16]:
random_value

1.5409589261084893

# 5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun

In [17]:
random_matrix = np.random.randn(5, 5)


In [18]:
random_matrix

array([[-1.60137519,  0.11222241,  0.27254234,  0.49485399, -1.06911626],
       [ 1.15534228, -1.17015051,  0.68329382,  2.7029259 ,  0.32324265],
       [-2.14304311,  0.47105087,  2.18576477, -1.32632249, -1.68875836],
       [-1.11684114, -0.16061689,  0.622346  , -1.22373259, -0.37880909],
       [-0.49242909,  0.02132405,  0.74528551, -1.45238815, -0.49911347]])

# 1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun

In [20]:
my_array = np.linspace(1, 5, 20)


In [22]:
my_array

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

# Array Indekslenmesi

In [50]:
arr  = np.arange(1,101).reshape(10,10)


In [25]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

# Indeks işlemlerini kullanarak aşağıdaki sonuçları elde etmeye çalışın


In [27]:
selected_section = arr[4:, 0:]


In [28]:
selected_section

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [29]:
selected_section = arr[6:, 4:]


In [30]:
selected_section

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [31]:
selected_section = arr[0:3, 2:4]


In [32]:
selected_section

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [38]:
selected_section = arr[0:3, 1]

In [39]:
selected_section

array([ 2, 12, 22])

In [43]:
selected_section = arr[0:3, 1:2]


In [44]:
selected_section


array([[ 2],
       [12],
       [22]])

In [53]:
selected_column = arr[:, 9]


In [54]:
selected_section


array([[ 2],
       [12],
       [22]])

# Array Operasyonları


In [55]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [56]:
arr1

array([[1, 2, 0],
       [3, 4, 0],
       [2, 4, 4]])

In [57]:
arr2

array([[1, 2, 1],
       [4, 0, 1],
       [1, 4, 3]])

# İki Matrisi Toplayın

In [58]:
result = np.add(arr1, arr2)


In [59]:
result

array([[2, 4, 1],
       [7, 4, 1],
       [3, 8, 7]])

# İki Matrisi Çarpın

In [63]:
result = np.dot(arr1, arr2)


In [64]:
result

array([[ 9,  2,  3],
       [19,  6,  7],
       [22, 20, 18]])

# arr1 matrisinin tüm elemanlarının ortalamasını bulun

In [72]:
average = np.mean(arr1)


In [73]:
average

2.2222222222222223

# arr1 matrisinin tüm elemanlarının toplamını bulun# arr1 matrisinin tüm elemanlarının toplamını bulun

In [74]:
total = np.sum(arr1)


In [75]:
total

20

In [76]:
arr1

array([[1, 2, 0],
       [3, 4, 0],
       [2, 4, 4]])