In [6]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [7]:
arr1

array([1, 2, 3, 4, 5])

In [8]:
arr2


array([ 6,  7,  8,  9, 10])

In [9]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [10]:
arr1 * arr2  # Inner Product(İç Çarpım)


array([ 6, 14, 24, 36, 50])

In [11]:
arr1 + 10


array([11, 12, 13, 14, 15])

In [12]:
arr1 - 10

array([-9, -8, -7, -6, -5])

In [13]:
arr2 - 2


array([4, 5, 6, 7, 8])

In [14]:
arr1 / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [15]:
arr2 ** 2

array([ 36,  49,  64,  81, 100], dtype=int32)

In [16]:
arr1

array([1, 2, 3, 4, 5])

In [17]:
np.sqrt(arr1)


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])